management:
  security:
    enabled: false
logging:
  level:
    org.springframework.boot: INFO
endpoints:
  health: #展示系统的各种组件运行状态、硬盘使用情况
    sensitive: false
  metrics: #统计系统当前的一些瞬时信息
    sensitive: false
  dump: #系统当前的线程信息
    sensitive: false
  env: #展示系统变量和spring boot的应用变量
    sensitive: false
  trace: #显示最近的请求响应对，默认最多缓存100条
    sensitive: false
  autoconfig: #展示所有auto-configration候选者，以及它们被应用或未被应用的原因
    sensitive: false
  info: #显示应用自定义信息
    sensitive: false
  configprops: #显示所有被@ConfigurationProperties标识的Bean的信息列表
    sensitive: false
  mappings: #显示所有被@RequestMapping标识的URL列表
    sensitive: false
  shutdown: #允许以POST方式关闭应用
    sensitive: false
  beans: #显示所有Spring Bean的信息
    sensitive: false

server:
  port: 5678

sidecar:
  port: 8081
  health-uri: http://localhost:8081/sidecar/health.json

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
    healthcheck:
      enabled： true    #开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
      lease-renewal-interval-in-seconds: 5    #续约更新时间间隔（默认30秒）
      lease-expiration-duration-in-seconds: 15    #续约到期时间（默认90秒）
