logging:
  level:
    org.springframework.boot: INFO
    
server:
  display-name: kcloud-config-center
  port: 8888
  tomcat:
    max-threads: 2
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kazeki/kcloud
          searchPaths: kcloudConfig
