server:
  display-name: kcloud-config-center
  port: 8888
spring:
  application:
    name: kcloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kazeki/kcloud
          searchPaths: kcloudConfig
