logging:
  level:
    ROOT: info
    org.springframework.cloud: trace
    org.springframework.boot: info

server:
  display-name: kcloud-config-center
  port: 8888
  tomcat:
    max-threads: 2
    
#spring:
  #cloud:
    #config:
      #server:
        #git:
          #uri: https://github.com/kazeki/kcloud.git
          #uri: https://github.com/kazeki/kcloud.git
          #uri: git@github.com:kazeki/kcloud.git
          #searchPaths: kcloudConfig
          #username: "chen.feng.07@163.com"
          #password: "chenfeng308,"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
    healthcheck:
      enabled： true    #开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    lease-renewal-interval-in-seconds: 5    #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 15    #续约到期时间（默认90秒）  
    
security:
    user:
      name: kazeki
      password: kazeki
