server:
  port: 80
spring:
  application:
    name: kcloud-home
  cloud:
    config:
      uri: http://localhost:${config.port:8888}
      name: kcloud-home
      profile: ${config.profile:dev}
  config:
    name: application
logging:
  level:
    org.springframework.boot: ERROR