logging:
  level:
    org.springframework.boot: INFO
    
server:
  port: 9999

system:
  greeting: Welcome to KCloud! from application
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/