logging:
  level:
    org.springframework.boot: ERROR
endpoints:
  health: #展示系统的各种组件运行状态、硬盘使用情况
    sensitive: false
  metrics: #统计系统当前的一些瞬时信息
    sensitive: false
  dump: #系统当前的线程信息
    sensitive: false
  env: #展示系统变量和spring boot的应用变量
    sensitive: false
  trace: #显示最近的请求响应对，默认最多缓存100条
    sensitive: false
  autoconfig: #展示所有auto-configration候选者，以及它们被应用或未被应用的原因
    sensitive: false
  info: #显示应用自定义信息
    sensitive: false
  configprops: #显示所有被@ConfigurationProperties标识的Bean的信息列表
    sensitive: false
  mappings: #显示所有被@RequestMapping标识的URL列表
    sensitive: false
  shutdown: #允许以POST方式关闭应用
    sensitive: false
  beans: #显示所有Spring Bean的信息
    sensitive: false

# 通过访问 /info 可以获得以下自定义数据
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  poweredBy: kazeki

