management:
  security:
    enabled: false
# 通过访问 /info 可以获得以下自定义数据
info:
  app:
    name: ${spring.application.name}
    profile: ${spring.profiles.active}
  build:
    artifactId: '@project.artifactId@'
    version: '@project.version@'
  security: ${management.security.enabled}
  configfile: git-application-dev
  fromApplicationDev: Hi

logging:
  level:
    org.springframework.boot: info
endpoints:
  health: #展示系统的各种组件运行状态、硬盘使用情况
    sensitive: true
  metrics: #统计系统当前的一些瞬时信息
    sensitive: true
  dump: #系统当前的线程信息
    sensitive: true
  env: #展示系统变量和spring boot的应用变量
    sensitive: true
  trace: #显示最近的请求响应对，默认最多缓存100条
    sensitive: true
  autoconfig: #展示所有auto-configration候选者，以及它们被应用或未被应用的原因
    sensitive: true
  info: #显示应用自定义信息
    sensitive: true
  configprops: #显示所有被@ConfigurationProperties标识的Bean的信息列表
    sensitive: true
  mappings: #显示所有被@RequestMapping标识的URL列表
    sensitive: true
  shutdown: #允许以POST方式关闭应用
    sensitive: true
  beans: #显示所有Spring Bean的信息
    sensitive: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled： true    #开启健康检查（需要spring-boot-starter-actuator依赖）
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 默认为0.1
      percentage: 1.0
