# 通过访问 /info 可以获得以下自定义数据
info:
  app:
    name: ${spring.application.name}
    profile: ${spring.profiles.active}
  build:
    artifactId: '@project.artifactId@'
    version: '@project.version@'
  security: ${management.security.enabled}
  configfile: git-KcloudEurekaServer
  fromKcloudEurekaServer: Hi
eureka:
  instance:
    #perferIpAddress: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true            #是否开启自我保护，开启时将不会剔除无效节点
    eviction-interval-timer-in-ms: 10000     #清理无效节点的时间间隔（单位毫秒，默认是60000）
spring:
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        serviceId: kcloud-config-center
